In [33]:
import yfinance as yf 
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
'''

EACH STRATEGY SHOULD FOLLOW THE FOLLOWING THREE STEPS

1) ACQUIRE THE DATA 

2) DEFINE THE STRATEGY 

3) TEST THE STRATEGY


'''

'\n\nEACH STRATEGY SHOULD FOLLOW THE FOLLOWING THREE STEPS\n\n1) ACQUIRE THE DATA \n\n2) DEFINE THE STRATEGY \n\n3) TEST THE STRATEGY\n\n\n'

In [35]:
'''
EXPONENTIAL MOVING AVERAGE FORMULA: (Current Price - Previous EMA) * Multiplier + Previous EMA
'''

'\nEXPONENTIAL MOVING AVERAGE FORMULA: (Current Price - Previous EMA) * Multiplier + Previous EMA\n'

In [36]:
TICKER = "SPY"
WINDOW = 8
MULTIPLIER = 2 / (WINDOW + 1)

In [46]:
def load_dataset(symbol):
    df = yf.download(TICKER, period="max")
    df.columns = df.columns.get_level_values(0)
    return pd.DataFrame(df)

In [47]:
df = load_dataset(TICKER)
df

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Date
1993-01-29   24.175377   24.192571   24.072210   24.192571   1003200
1993-02-01   24.347311   24.347311   24.192561   24.192561    480500
1993-02-02   24.398907   24.416101   24.278546   24.330129    201300
1993-02-03   24.656834   24.674028   24.416111   24.433306    529400
1993-02-04   24.759991   24.811574   24.467685   24.742796    531500
...                ...         ...         ...         ...       ...
2026-05-07  731.580017  736.130005  729.750000  735.049988  51724600
2026-05-08  737.619995  738.080017  734.570007  734.929993  47227100
2026-05-11  739.299988  740.789978  736.450012  736.450012  44024000
2026-05-12  738.179993  738.840027  731.830017  736.890015  54185300
2026-05-13  742.309998  743.900024  735.469971  738.469971  37500556

[8379 rows x 5 columns]

In [51]:
# calculate the ema using the sma
def exponential_moving_average(df):
    try:
        df["SMA"] = df["Close"].rolling(window=WINDOW).mean()
        df["EMA"] = df["SMA"].ewm(span=WINDOW, adjust=False).mean()
    except Exception as e:
        print(f"error: {e}")
    return df.dropna()

In [52]:
df = exponential_moving_average(df)
df

Price,Close,High,Low,Open,Volume,SMA,EMA
Date,,,,,,,
1993-02-09,24.570852,24.656824,24.519269,24.656824,122100,24.549359,24.549359
1993-02-10,24.605242,24.622436,24.502075,24.570853,379600,24.603092,24.561300
1993-02-11,24.725603,24.828770,24.639631,24.639631,19500,24.650379,24.581095
1993-02-12,24.536463,24.691213,24.536463,24.691213,42500,24.667573,24.600313
1993-02-16,23.917458,24.467679,23.883069,24.467679,374800,24.575151,24.594721
...,...,...,...,...,...,...,...
2026-05-07,731.580017,736.130005,729.750000,735.049988,51724600,721.221260,714.357485
2026-05-08,737.619995,738.080017,734.570007,734.929993,47227100,724.462509,716.603046
2026-05-11,739.299988,740.789978,736.450012,736.450012,44024000,727.927505,719.119593
2026-05-12,738.179993,738.840027,731.830017,736.890015,54185300,730.367508,721.619129
2026-05-13,742.309998,743.900024,735.469971,738.469971,37500556,733.075005,724.164879